[workspace]
resolver = "3"
members = [
    "crates/sonalloy-core",
    "crates/sonalloy-dsp-sys",
    "crates/sonalloy-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
